<template>
    <div class="goods">
        <Boxs></Boxs>
        <Around class="around1" :roundData1="roundData1"></Around>
        <Around class="around2" :roundData1="roundData2"></Around>
        <Around class="around3" :roundData1="roundData3"></Around>
    </div>
</template>
<script>
import Boxs from '../../components/goods/Boxs.vue'
import Around from '../../components/goods/Around.vue'

export default {
    data(){
        return{
            roundData1:{
                title:'搭配',
                menu:[{
                    name:'热门',
                    key:'hot',
                    goods:[{
                        name:'小米AI音箱',
                        price:'299元',
                        pic:'http://i1.mifile.cn/a1/pms_1522666970.27937468.jpg?width=150&height=150',
                        rank:'4.9万人评价',
                        evaluate:'狂拽炫酷吊炸天，功能慢慢摸索中！',
                        origin:'来自于 680216907 的评价'
                    },{
                        name:'小米小爱音箱mini',
                        price:'169元',
                        pic:'http://i1.mifile.cn/a1/pms_1524571235.37826274.jpg?width=150&height=150',
                        rank:'8041人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米移动电源10000mAh高配版',
                        price:'149元',
                        pic:'http://i1.mifile.cn/a1/pms_1481269289.59498154.jpg?width=150&height=150',
                        rank:'2.4万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'新小米移动电源2(10000mAh)',
                        price:'79元',
                        pic:'http://i1.mifile.cn/a1/pms_1513857241.9291821.jpg?width=150&height=150',
                        rank:'1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米电源移动2C 20000mAh',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/pms_1505264799.43246303.jpg?width=150&height=150',
                        rank:'2.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米USB充电器快充版(18W)',
                        price:'29.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1507877361.06147174.jpg?width=150&height=150',
                        rank:'5391人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米活塞耳机 清新版',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1482321199.12589253.jpg?width=150&height=150',
                        rank:'10.8万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米运动蓝牙耳机mini',
                        price:'169元',
                        pic:'http://i1.mifile.cn/a1/pms_1502093110.00979492.jpg?width=80&height=80',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'耳机音响',
                    key:'headset',
                    goods:[{
                        name:'小米双单元半入耳式耳机',
                        price:'69元',
                        pic:'http://i1.mifile.cn/a1/pms_1521442671.5222520!220x220.jpg',
                        rank:'2718人评论',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米胶囊耳机',
                        price:'69元',
                        pic:'http://i1.mifile.cn/a1/T1SkV_BCd_1RXrhCrK!220x220.jpg',
                        rank:'5.3万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米降噪耳机Type-C版',
                        price:'299元',
                        pic:'http://i1.mifile.cn/a1/pms_1492587658.23552969!220x220.jpg',
                        rank:'8004人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米随身蓝牙音箱',
                        price:'69元',
                        pic:'http://i1.mifile.cn/a1/T1IdZgB5hv1RXrhCrK!220x220.jpg',
                        rank:'2.9万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米蓝牙耳机青春版',
                        price:'59元',
                        pic:'http://i1.mifile.cn/a1/pms_1478248721.42297795!220x220.jpg',
                        rank:'5万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米运动蓝牙耳机mini',
                        price:'169元',
                        pic:'http://i1.mifile.cn/a1/pms_1502093110.00979492!220x220.jpg',
                        rank:'1.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米蓝牙音频接收器',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1499161620.42031583!220x220.jpg',
                        rank:'8112人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米小钢炮蓝牙音箱2 ',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/T1F5K_BjVv1RXrhCrK!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'电源',
                    key:'power',
                    goods:[{
                        name:'小米移动电源10000mAh高配版',
                        price:'149元',
                        pic:'http://i1.mifile.cn/a1/pms_1481273468.72564539!220x220.jpg',
                        rank:'2.4万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米移动电源2C 20000mAh',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/pms_1505264799.43246303!220x220.jpg',
                        rank:'2.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米移动电源5000mAh',
                        price:'49元',
                        pic:'http://i1.mifile.cn/a1/T1pZbvBTET1RXrhCrK!220x220.jpg',
                        rank:'10.9万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米电源线收纳盒',
                        price:'49元',
                        pic:'http://i1.mifile.cn/a1/T1eKdgB4xv1RXrhCrK!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    },{
                        name:'10000mAh小米移动电源2',
                        price:'79元',
                        pic:'http://i1.mifile.cn/a1/pms_1476688190.21955893!220x220.jpg',
                        rank:'7万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米二合一数据线',
                        price:'19.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1478070969.5786053!220x220.jpg',
                        rank:'1.8万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'USB Type-C充电套装',
                        price:'15元',
                        pic:'http://i1.mifile.cn/a1/pms_1469410847.29693876!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米智能插线板',
                        price:'69元',
                        pic:'http://i1.mifile.cn/a4/T13mDQBjCT1RXrhCrK.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'电池存储卡',
                    key:'card',
                    goods:[{
                        name:'SanDisk 32GB存储卡（U3, 100MB/s）',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/pms_1509356199.1647812!220x220.jpg',
                        rank:'915人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米USB充电器（2口）',
                        price:'39元',
                        pic:'http://i1.mifile.cn/a1/pms_1484034162.02747540!220x220.jpg',
                        rank:'2.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'彩虹5号电池（10粒装）',
                        price:'9.9元',
                        pic:'http://i1.mifile.cn/a1/T1xxVTBghv1RXrhCrK!220x220.jpg',
                        rank:'12.5万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'睿米一分二点烟器',
                        price:'79元',
                        pic:'http://i1.mifile.cn/a1/pms_1492658221.34618453!220x220.jpg',
                        rank:'2147人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米USB充电器（4口）',
                        price:'59元',
                        pic:'http://i1.mifile.cn/a1/T1vFEjBbWT1RXrhCrK!220x220.jpg',
                        rank:'1.6万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米USB充电器快充版（18W）',
                        price:'29.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1507877361.06147174!220x220.jpg',
                        rank:'5391人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米车载充电器',
                        price:'49元',
                        pic:'http://i1.mifile.cn/a1/T142A_BXEv1RXrhCrK!220x220.jpg',
                        rank:'5.7万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'SanDisk 16GB存储卡（C10, 98MB/s）',
                        price:'54.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1509355060.24432575!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                }],
                demoPic:['http://i3.mifile.cn/a4/54581b2c-f88d-4415-9754-af83116346bd','http://i3.mifile.cn/a4/f7da6234-7159-414a-a2ea-8832af89b4f1'],

            },
            roundData2:{
                title:'配件',
                menu:[{
                    name:'热门',
                    key:'hot',
                    goods:[{
                        name:'黑鲨游戏钢化膜',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1526888961.86752709.jpg?width=150&height=150',
                        rank:'168人评价',
                        evaluate:'狂拽炫酷吊炸天，功能慢慢摸索中！',
                        origin:'来自于 680216907 的评价'
                    },{
                        name:'小米 8 标准高透贴膜',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1527840584.43636811.jpg?width=150&height=150',
                        rank:'148人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'黑鲨游戏手机保护壳',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1525862487.19934098.png?width=150&height=150',
                        rank:'51人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米6X 极简保护壳',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1524466977.94886383.jpg?width=150&height=150',
                        rank:'513人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'Mi MIX 2S 硅胶保护套',
                        price:'59元',
                        pic:'http://i1.mifile.cn/a1/pms_1523354403.31383469.png?width=150&height=150',
                        rank:'529人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米MIX 2S 标准高透膜',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1522140924.30981214.jpg?width=150&height=150',
                        rank:'682人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'Mi MIX 2S 真皮保护套',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1522142136.45425672.jpg?width=150&height=150',
                        rank:'170人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'MIX 2全陶瓷版极简保护壳',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1509852701.75968362.jpg?width=80&height=80',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'保护套',
                    key:'cover',
                    goods:[{
                        name:'小米Note 3  硅胶保护套 蓝色',
                        price:'26元',
                        pic:'http://i1.mifile.cn/a1/pms_1505875659.46176354!220x220.jpg',
                        rank:'5107人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米Note 4X 高透软胶保护套 透明',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1486980879.11199962!220x220.jpg',
                        rank:'8279人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'MIX 2全陶瓷版极简保护壳 黑色',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1509852703.79453120!220x220.jpg',
                        rank:'1064人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米6X 极简保护壳 黑色',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1524467046.18799928!220x220.jpg',
                        rank:'513人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米5X 幻彩保护壳 星空黑',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1501555227.53753564!220x220.jpg',
                        rank:'4688人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米note4X 智能显示保护套',
                        price:'39元',
                        pic:'http://i1.mifile.cn/a1/pms_1488522312.21011606!220x220.jpg',
                        rank:'3463人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米 5 Plus 极简防摔保护套 黑色',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1512957185.6636673!220x220.jpg',
                        rank:'1541人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米 5 极简保护套 黑色',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1512894733.40646204!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'贴膜',
                    key:'velamen',
                    goods:[{
                        name:'红米Note 4X 标准高透贴膜',
                        price:'10元',
                        pic:'http://i1.mifile.cn/a4/xmad_14987297093922_POaTU.jpg',
                        rank:'1.4万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米6X 标准高透贴膜',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1524466931.58435208!220x220.jpg',
                        rank:'555人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米S2 标准高透膜',
                        price:'10元',
                        pic:'http://i1.mifile.cn/a1/pms_1526349330.12883818!220x220.jpg',
                        rank:'14人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米Max2 高透保护膜',
                        price:'10元',
                        pic:'http://i1.mifile.cn/a1/pms_1496238415.93753872!220x220.jpg',
                        rank:'4971人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米 5 Plus 标准钢化玻璃膜',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1512898082.47038866!220x220.jpg',
                        rank:'950人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'红米4标准版 标准高透贴膜',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1482136232.14896578!220x220.jpg',
                        rank:'1005人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'Mi MIX 2S 标准高透膜',
                        price:'29元',
                        pic:'http://i1.mifile.cn/a1/pms_1522140924.30981214!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米6 标准高透贴膜',
                        price:'10元',
                        pic:'http://i1.mifile.cn/a1/pms_1493284697.69911065!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'其他配件',
                    key:'other',
                    goods:[{
                        name:'悦米机械键盘',
                        price:'299元',
                        pic:'http://i1.mifile.cn/a1/pms_1490702347.3628109!220x220.png',
                        rank:'2224人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米指环支架 金色',
                        price:'19元',
                        pic:'http://i1.mifile.cn/a1/pms_1482221011.26064844!220x220.jpg',
                        rank:'2.4万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米USB充电器（10W）',
                        price:'19.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1507878667.12359513!220x220.jpg',
                        rank:'2736人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米USB充电器快充版（18W）',
                        price:'29.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1507877361.06147174!220x220.jpg',
                        rank:'5394人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米便携鼠标',
                        price:'94元',
                        pic:'http://i1.mifile.cn/a1/pms_1488533926.06453673!220x220.jpg',
                        rank:'1.6万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'USB-C至HDMI多功能转接器',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/pms_1469523170.25518983!220x220.jpg',
                        rank:'2012人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'USB Type-C 转接头',
                        price:'5元',
                        pic:'http://i1.mifile.cn/a1/T1xLxQBgVT1RXrhCrK!220x220.jpg',
                        rank:'9.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米二合一数据线100cm',
                        price:'24.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1480066629.77799920!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                }],
                demoPic:['http://i3.mifile.cn/a4/aa163c95-2890-4227-967c-a05ccec6c4a9','http://i3.mifile.cn/a4/363032e6-b043-4854-a8cc-8909df918f02'],

            },
            roundData3:{
                title:'周边',
                menu:[{
                    name:'热门',
                    key:'hot',
                    goods:[{
                        name:'TS尼龙偏光太阳镜 米家定制灰色',
                        price:'199元',
                        pic:'http://i1.mifile.cn/a1/pms_1492999959.43955760!220x220.jpg',
                        rank:'1.4万人评价',
                        evaluate:'狂拽炫酷吊炸天，功能慢慢摸索中！',
                        origin:'来自于 680216907 的评价'
                    },{
                        name:'米兔招财猫足金吊坠',
                        price:'888元',
                        pic:'http://i1.mifile.cn/a1/pms_1522309592.89679012!220x220.jpg',
                        rank:'570人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米短袖T恤 两件装',
                        price:'89元',
                        pic:'http://i1.mifile.cn/a1/pms_1522636275.74216007!220x220.jpg',
                        rank:'3824人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H记忆绵护椎腰靠',
                        price:'89元',
                        pic:'http://i1.mifile.cn/a1/pms_1521026661.04345181!220x220.jpg',
                        rank:'782人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'自动折叠伞 黑',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1508311018.31143247!220x220.jpg',
                        rank:'9295人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米棒球帽 藏蓝',
                        price:'49元',
                        pic:'http://i1.mifile.cn/a1/pms_1522311796.15496400!220x220.jpg',
                        rank:'944人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'贝医生巴氏牙刷(四色装)',
                        price:'39.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1502258923.87257653!220x220.jpg',
                        rank:'1.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H乳胶弹簧静音床垫',
                        price:'1599元',
                        pic:'http://i1.mifile.cn/a1/pms_1502097740.52392774!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'出行',
                    key:'travel',
                    goods:[{
                        name:'霍尼韦尔新风口罩米家定制',
                        price:'249元',
                        pic:'http://i1.mifile.cn/a1/pms_1514354852.36577901!220x220.jpg',
                        rank:'41人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'米家运动鞋2',
                        price:'199元',
                        pic:'http://i1.mifile.cn/a1/pms_1528368095.99082693!220x220.jpg',
                        rank:'1694人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'90分旅行箱 24寸',
                        price:'349元',
                        pic:'http://i1.mifile.cn/a1/T1PHVjBXxv1RXrhCrK!220x220.jpg',
                        rank:'2.9万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'Free Tie真皮板鞋 米家定制',
                        price:'199元',
                        pic:'http://i1.mifile.cn/a1/pms_1504510139.65413172!220x220.jpg',
                        rank:'1.5万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米经典商务双肩包',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/T1DuxvB4D_1RXrhCrK!220x220.jpg',
                        rank:'1.8万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'TS偏光太阳镜   米家定制',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1500282577.40987685!220x220.jpg',
                        rank:'8109人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'TS尼龙偏光太阳镜 米家定制',
                        price:'199元',
                        pic:'http://i1.mifile.cn/a1/pms_1492999959.43955760!220x220.jpg',
                        rank:'1.4万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米纪念款围巾（去探索）',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/pms_1478762755.55733411!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'居家',
                    key:'live',
                    goods:[{
                        name:'8H护颈乳胶枕',
                        price:'239元',
                        pic:'http://i1.mifile.cn/a1/pms_1472711253.2453066!220x220.jpg',
                        rank:'2万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H标准乳胶枕',
                        price:'159元',
                        pic:'http://i1.mifile.cn/a1/pms_1472710764.55986027!220x220.jpg',
                        rank:'1.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H多功能护颈枕U1',
                        price:'79元',
                        pic:'http://i1.mifile.cn/a1/pms_1481178479.88974286!220x220.jpg',
                        rank:'8035人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H乳胶弹簧静音床垫',
                        price:'1899元',
                        pic:'http://i1.mifile.cn/a1/pms_1502097740.52392774!220x220.jpg',
                        rank:'654人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H乳胶床垫',
                        price:'999元',
                        pic:'http://i1.mifile.cn/a1/pms_1493030484.68163070!220x220.jpg',
                        rank:'3127人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H懒人舒适沙发',
                        price:'599元',
                        pic:'http://i1.mifile.cn/a1/pms_1502195257.33325849!220x220.jpg',
                        rank:'162人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H蝶形护颈记忆绵枕',
                        price:'129元',
                        pic:'http://i1.mifile.cn/a1/pms_1510124061.78733980!220x220.jpg',
                        rank:'1300人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'8H鹅绒被',
                        price:'1599元',
                        pic:'http://i1.mifile.cn/a1/pms_1508820001.68866329!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'生活周边',
                    key:'life',
                    goods:[{
                        name:'花花草草监测仪',
                        price:'49元',
                        pic:'http://i1.mifile.cn/a1/pms_1465724476.99494960!220x220.jpg',
                        rank:'8011人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'TS眼镜架 米家定制',
                        price:'249元',
                        pic:'http://i1.mifile.cn/a1/pms_1508483196.21912684!220x220.jpg',
                        rank:'1204人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'TS儿童防蓝光护目镜',
                        price:'199元',
                        pic:'http://i1.mifile.cn/a1/pms_1508744600.02281018!220x220.jpg',
                        rank:'1059人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'最生活毛巾·青春系列',
                        price:'19.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1479972875.00224492!220x220.jpg',
                        rank:'6.9万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'最生活浴巾·青春系列',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1479972928.16946623!220x220.jpg',
                        rank:'4579人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'米家wiha精修螺丝刀套装',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1501724155.59847725!220x220.jpg',
                        rank:'1.3万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'自动折叠伞',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/pms_1500369741.38796229!220x220.jpg',
                        rank:'9295人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'最生活方巾·青春系列',
                        price:'14.9元',
                        pic:'http://i1.mifile.cn/a1/pms_1503051892.94593687!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                },{
                    name:'箱包',
                    key:'bag',
                    goods:[{
                        name:'小米极简都市双肩包',
                        price:'149元',
                        pic:'http://i1.mifile.cn/a1/T1a3DvB7hv1RXrhCrK!220x220.jpg',
                        rank:'3.1万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米经典商务双肩包',
                        price:'99元',
                        pic:'http://i1.mifile.cn/a1/T1DuxvB4D_1RXrhCrK!220x220.jpg',
                        rank:'1.8万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米商旅多功能双肩包',
                        price:'199元',
                        pic:'http://i1.mifile.cn/a1/pms_1489390614.78781530!220x220.jpg',
                        rank:'4251人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米学院休闲双肩包',
                        price:'79元',
                        pic:'http://i1.mifile.cn/a1/pms_1497672764.01987286!220x220.jpg',
                        rank:'9976人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'90分旅行箱 20寸',
                        price:'',
                        pic:'http://i1.mifile.cn/a1/T1OQ__B7Zv1RXrhCrK!220x220.jpg',
                        rank:'2.8万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'90分旅行箱 24寸',
                        price:'349元',
                        pic:'http://i1.mifile.cn/a1/T1CDbjBgAT1RXrhCrK!220x220.jpg',
                        rank:'2.9万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'小米多功能都市休闲胸包',
                        price:'69元',
                        pic:'http://i1.mifile.cn/a1/T1FtKgBvZv1RXrhCrK!220x220.jpg',
                        rank:'4.4万人评价',
                        evaluate:'',
                        origin:''
                    },{
                        name:'90分户外休闲双肩包',
                        price:'249元',
                        pic:'http://i1.mifile.cn/a1/pms_1508493128.86019237!220x220.jpg',
                        rank:'',
                        evaluate:'',
                        origin:''
                    }]
                }],
                demoPic:['http://i1.mifile.cn/a4/xmad_15284596646115_wNMGC.jpg','http://i1.mifile.cn/a4/xmad_15162458631619_LTmcI.jpg'],

            }
        }
    },
    components:{
        Boxs,
        Around
    }
}
</script>
<style>
.goods{
    position: absolute;
    width: 90%;
    height: auto;
    top:803px;
    left: 5%;

}
.around1{
    position: absolute;
    top:698px;
}
.around2{
    position: absolute;
    top:1410px;
}
.around3{
    position: absolute;
    top:2122px;
}
</style>
